/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cab.Invoice.Generator;

import org.junit.Test;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class CabInvoiceTest {
	@Test
    public void givenDistanceAndTime_ShouldReturnTotalFare() {
    	CabInvoice cabInvoice = new CabInvoice();
    	double distance = 2.0;
    	int time = 5;
    	double fare = cabInvoice.calculateFare(distance, time);
    	Assert.assertEquals(25, fare, 0.0);
    }
}
