/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cab.Invoice.Generator;

public class CabInvoice {
    public boolean someLibraryMethod() {
        return true;
    }
}
